# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /opt/engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /opt/engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/engine/CMakeFiles /opt/engine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named etest_main

# Build rule for target.
etest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 etest_main
.PHONY : etest_main

# fast build rule for target.
etest_main/fast:
	$(MAKE) -f util/CMakeFiles/etest_main.dir/build.make util/CMakeFiles/etest_main.dir/build
.PHONY : etest_main/fast

#=============================================================================
# Target rules for targets named test_etest

# Build rule for target.
test_etest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_etest
.PHONY : test_etest

# fast build rule for target.
test_etest/fast:
	$(MAKE) -f util/CMakeFiles/test_etest.dir/build.make util/CMakeFiles/test_etest.dir/build
.PHONY : test_etest/fast

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) -f engine_race/CMakeFiles/engine.dir/build.make engine_race/CMakeFiles/engine.dir/build
.PHONY : engine/fast

#=============================================================================
# Target rules for targets named test_hash

# Build rule for target.
test_hash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hash
.PHONY : test_hash

# fast build rule for target.
test_hash/fast:
	$(MAKE) -f engine_race/CMakeFiles/test_hash.dir/build.make engine_race/CMakeFiles/test_hash.dir/build
.PHONY : test_hash/fast

#=============================================================================
# Target rules for targets named test_engine

# Build rule for target.
test_engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_engine
.PHONY : test_engine

# fast build rule for target.
test_engine/fast:
	$(MAKE) -f test/CMakeFiles/test_engine.dir/build.make test/CMakeFiles/test_engine.dir/build
.PHONY : test_engine/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... etest_main"
	@echo "... test_etest"
	@echo "... engine"
	@echo "... test_hash"
	@echo "... test_engine"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

